version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  client: 
    build: 
      dockerfile: Dockerfile
      context: ./client
    container_name: client
    restart: always
    ports:
      - 3001:80

  backend:
    build:
     dockerfile: Dockerfile
     context: ./backend
    container_name: backend
    restart: always
    depends_on:
      - mongo
    ports:
      - 5000:5000
