---
- name: Set up a yolo ecommerce
  hosts: my_vm
  gather_facts: no
  become_user: root

  tasks:
    - name: Check SSH connectivity and ping
      ping:

    - name: Install python3 version
      yum:
        name: 
          - python3

    - name: Install Docker 
      raw: curl -fsSl https://get.docker.com/ | sh

    - name: Assign Docker  To privileges
      raw: sudo usermod -aG docker $(whoami)

    - name: Start Docker 
      raw: sudo systemctl start docker

    - name: Install Git 
      raw: sudo yum install git

    - name: Create directory
      file:
        path: /yolo
        state: directory
        mode: 0755