---
- name: Set up a yolo ecommerce
  hosts: my_vm
  gather_facts: no
  become_user: root

  tasks:
    - name: Check SSH connectivity and ping
      ping:

    - name: Install python3 version
      yum:
        name: 
          - python3