---
- name: App containerisation with ansible
  hosts: localhost
  gather_facts: no
  become_user: root

tasks:
    - name: Check SSH connectivity and ping
      ping:

    - name: Install python3 version
      apt:
        name:
          - python3

    - name: Install Docker
      raw: curl -fsSL https://get.docker.com/ | sh

    - name: Assign Docker to privileges
      raw: sudo usermod -aG docker $(whoami)

     - name: Start Docker
      raw: sudo systemctl start docker

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Create directory
      file:
        path: /yolo
        state: directory
        mode: 0755


