---
- name: App containerisation with ansible
  hosts: localhost
  gather_facts: no
  become_user: root

tasks:
    - name: Check SSH connectivity and ping
      ping:

    - name: Install python3 version
      apt:
        name:
          - python3

